### ISSUE TITLE
create a function that draws the track based of array

### ISSUE THREAD

**Issue by Bradskine** [Bradskine/Lv3-Programming#1]
I have got the track to draw following coaradiantes in current track array and had a width but does not full the squares in graph for the 1st and last section of the track

**Comment by Bradskine** [comment]
this was happening becasue i was drawing to the center of the squares with a width to fix this i just added 2 ifs in the 
draw tarck function that add an extra bit of track at the start and the end.

**Comment by solutionai199** [comment]
Nice
